### PR TITLE
upgrade to guzzle 6

### PR DESCRIPTION
**Pull request by jdeniau**
I moved from PSR-0 to PSR-4 too

### CODE REVIEW

**Comment by MattKetmo** [comment]
Thanks but the PR is made from an older version which conflicts with master :)

**Comment by jdeniau** [comment]
Fixed

**Comment by jdeniau** [comment]
Hmmm... it seems that it's still WIP because the `getDefaultUserAgent` method does not exists anymore. 
I will take a look tomorrow

**Comment by jdeniau** [comment]
Seems OK, I tried to update translations with it and it worked like a charm ;)

**Comment by MattKetmo** [comment]
:+1:

**Pull request merged**
